### PR TITLE
Collaborative project - Embedding images and video

### PR DESCRIPTION
**Pull request by marcoshdezcam**
**Collaborative project - Embedding images and video**
YouTube Clone

In this project:
-Created a YouTube Mockup page using CSS Grid and Flexbox

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!
### Nice job! WOW, project looks! :+1: 

### But your project needs a few changes before it can be approved.

#### Page structure

##### Video
* It has a share button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

##### In original version of this page "share" - it`s button
share

* Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history 
screen
### Make changes and submit another code review request.

* Kindly recommended checking CSS file https://jigsaw.w3.org/css-validator/validator



css


*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Comment by addod19** [comment]
### Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Required changes  🔴

Hi Team! 😊
Good Job, README looks professional, descriptive commits, no markup validator errors.
The project looks great.

To approve the project we need to fix the following: 

- Kindly fix the comments requested by the previous reviewer.
- Remove commented code
- Fix errors in CSS validator [link](https://jigsaw.w3.org/css-validator)

**Comment by guirecordon** [comment]
Thank you, Anna!
I made the changes as you both asked. 
Thank you, Daniel, for the fixed link to the CSS validator. 
Please let me know how it looks! 
Thank you.

**Review by mosesogwo — APPROVED** [review]
### :trophy:Congratulations! Your project is good to :airplane: .

You may now merge to master and submit a project completion form.

Happy Coding.

### Status: Approved!

**Pull request merged**
